title: Portfolio
baseurl: /portfolio
permalink: pretty

# Build
exclude: [
'.git',
'node_modules',
'source',
'gulp',
'bower.json',
'gulpfile.js',
'package.json',
'README.md',
'build'
]

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: ["index", "compress"]
